# Generated by Django 4.1.7 on 2023-06-07 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('srevicetype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.CharField(blank=True, default=True, max_length=10)),
                ('amenities', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('operator',),
            },
        ),
    ]
