# Generated by Django 4.1.7 on 2023-06-08 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='service',
            name='ends_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
