# Generated by Django 4.1.7 on 2023-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_service_date_time_service_ends_at_service_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_time',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
