# Generated by Django 4.1.7 on 2023-06-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_service_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='date_time',
            new_name='date',
        ),
    ]
