# Generated by Django 4.1.7 on 2023-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_date_time_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
